from ekphrasis.classes.tokenizer import SocialTokenizer
from ekphrasis.classes.spellcorrect import SpellCorrector
from ekphrasis.classes.preprocessor import TextPreProcessor

sp = SpellCorrector(corpus="twitter")


EMOTICONS_TOKEN = {
    ':*': '<kiss>',
    ':-*': '<kiss>',
    ':x': '<kiss>',
    ':-)': '<happy>',
    ':-))': '<happy>',
    ':-)))': '<happy>',
    ':-))))': '<happy>',
    ':-)))))': '<happy>',
    ':-))))))': '<happy>',
    ':)': '<happy>',
    ':))': '<happy>',
    ':)))': '<happy>',
    ':))))': '<happy>',
    ':)))))': '<happy>',
    ':))))))': '<happy>',
    ':)))))))': '<happy>',
    ':o)': '<happy>',
    ':]': '<happy>',
    ':3': '<happy>',
    ':c)': '<happy>',
    ':>': '<happy>',
    '=]': '<happy>',
    '8)': '<happy>',
    '=)': '<happy>',
    ':}': '<happy>',
    ':^)': '<happy>',
    '|;-)': '<happy>',
    ":'-)": '<happy>',
    ":')": '<happy>',
    '\o/': '<happy>',
    '*\\0/*': '<happy>',
    ':-D': '<laugh>',
    ':D': '<laugh>',
    # '(\':': '<laugh>',
    '8-D': '<laugh>',
    '8D': '<laugh>',
    'x-D': '<laugh>',
    'xD': '<laugh>',
    'X-D': '<laugh>',
    'XD': '<laugh>',
    '=-D': '<laugh>',
    '=D': '<laugh>',
    '=-3': '<laugh>',
    '=3': '<laugh>',
    'B^D': '<laugh>',
    '>:[': '<sad>',
    ':-(': '<sad>',
    ':-((': '<sad>',
    ':-(((': '<sad>',
    ':-((((': '<sad>',
    ':-(((((': '<sad>',
    ':-((((((': '<sad>',
    ':-(((((((': '<sad>',
    ':(': '<sad>',
    ':((': '<sad>',
    ':(((': '<sad>',
    ':((((': '<sad>',
    ':(((((': '<sad>',
    ':((((((': '<sad>',
    ':(((((((': '<sad>',
    ':((((((((': '<sad>',
    ':-c': '<sad>',
    ':c': '<sad>',
    ':-<': '<sad>',
    ':<': '<sad>',
    ':-[': '<sad>',
    ':[': '<sad>',
    ':{': '<sad>',
    ':-||': '<sad>',
    ':@': '<sad>',
    ":'-(": '<sad>',
    ":'(": '<sad>',
    'D:<': '<sad>',
    'D:': '<sad>',
    'D8': '<sad>',
    'D;': '<sad>',
    'D=': '<sad>',
    'DX': '<sad>',
    'v.v': '<sad>',
    "D-':": '<sad>',
    '(>_<)': '<sad>',
    ':|': '<sad>',
    '>:O': '<surprise>',
    ':-O': '<surprise>',
    ':-o': '<surprise>',
    ':O': '<surprise>',
    '°o°': '<surprise>',
    'o_O': '<surprise>',
    'o_0': '<surprise>',
    'o.O': '<surprise>',
    'o-o': '<surprise>',
    '8-0': '<surprise>',
    '|-O': '<surprise>',
    ';-)': '<wink>',
    ';)': '<wink>',
    '*-)': '<wink>',
    '*)': '<wink>',
    ';-]': '<wink>',
    ';]': '<wink>',
    ';D': '<wink>',
    ';^)': '<wink>',
    ':-,': '<wink>',
    '>:P': '<tong>',
    ':-P': '<tong>',
    ':P': '<tong>',
    'X-P': '<tong>',
    'x-p': '<tong>',
    'xp': '<tong>',
    'XP': '<tong>',
    ':-p': '<tong>',
    ':p': '<tong>',
    '=p': '<tong>',
    ':-Þ': '<tong>',
    ':Þ': '<tong>',
    ':-b': '<tong>',
    ':b': '<tong>',
    ':-&': '<tong>',
    '>:\\': '<annoyed>',
    '>:/': '<annoyed>',
    ':-/': '<annoyed>',
    ':-.': '<annoyed>',
    ':/': '<annoyed>',
    ':\\': '<annoyed>',
    '=/': '<annoyed>',
    '=\\': '<annoyed>',
    ':L': '<annoyed>',
    '=L': '<annoyed>',
    ':S': '<annoyed>',
    '>.<': '<annoyed>',
    ':-|': '<annoyed>',
    '<:-|': '<annoyed>',
    ':-X': '<seallips>',
    ':X': '<seallips>',
    ':-#': '<seallips>',
    ':#': '<seallips>',
    'O:-)': '<angel>',
    '0:-3': '<angel>',
    '0:3': '<angel>',
    '0:-)': '<angel>',
    '0:)': '<angel>',
    '0;^)': '<angel>',
    '>:)': '<devil>',
    '>:D': '<devil>',
    '>:-D': '<devil>',
    '>;)': '<devil>',
    '>:-)': '<devil>',
    '}:-)': '<devil>',
    '}:)': '<devil>',
    '3:-)': '<devil>',
    '3:)': '<devil>',
    'o/\o': '<highfive>',
    '^5': '<highfive>',
    '>_>^': '<highfive>',
    '^<_<': '<highfive>',  # todo:fix tokenizer - MISSES THIS
    '<3': '<heart>'
}

LOGOGRAM = {
       'Gonna': 'going to ',
       "POS":" point-of-sale ",
        "omg": "oh my god ",
         "y'all": " you all ",
        "didnt": "doesn't exist",
      " DiDNT": "doesn't exist",
      "She'll": " she will ",
       "ya": "young adult",
       "ESPN": " Entertainment Sports Programming Network ",
        "AI": " artificial intelligence ",
         'IQ': 'intelligence quotient',
        'GDP': 'Gross Domestic Product',
        ' em ': 'them',
        'nthing': 'nothing',
        'samting': 'somthing',
        'dnot': 'do not',
        'thankyou':'thank you',
        'frnd': 'friend',
        'qstn': 'question',
        "nthng": 'nothing',
        "whatsup": 'what is up',
        'thnxx': 'thanks',
        "hppnd": 'happend',
        "isfor": 'is for',
        "wasn't": 'was not',
        'havent': 'have not',
        "replyme": 'reply me',
        "iscomputer": 'is computer',
        "whatsapp": 'what is application',
        'didnt': "did not",
        "thanx": 'thanks',
        "you've": 'you have',
        "ain't": 'can not',
        'nufn': 'nothing',
        "&":'and',
        "dn": 'do not',
        "nd": 'end',
        "doesn't": 'dose not',
        "i'm": 'i am',
        "aren't": 'are not',
        'wont': 'will not',
        'isnt': 'is not',
        'wht': 'what',
        "ur's": 'your is',
        'tme': 'time',
        'lol': 'laugh out loud',
        'slp': 'sleep',
        'tym': 'time',
        'wat': 'what',
        'hv': 'have',
        'ntng': 'nothing',
        "we're": 'we are',
        "plzz": 'please',
        "arn't": 'are not',
        'arnt': 'are not',
        'wouldnt': 'would not',
         "it’s": "it is",
        "shouldn't": 'should not',
        "couldn't": 'could not',
        "couldnt": 'could not',
        "it'll": "it will",
        "itll": 'it will',
        "whats": 'what is',
        "she's": 'she is',
        'shes': 'she is',
        "he's": 'he is',
        'hes': 'he is',
        "how's": 'how is',
        'hows': 'how is',
        "nt": 'nothing',
        "isn't":'is not',
        "dont":"do not",
        "when's":'when is',
        'whens':'when is',
        "there's":'there is',
        'its':'it is',
        "can't":"can not",
        "let's":'let us',
        'lets':'let us',
        "i've":'i have',
        'ive':'i have',
        "that's":'that is',
        'thats':'that is',
        "won't": 'will not',
        "what's": 'what is',
        "dosen't": 'dose not',
        'dosent':'dose not',
        "you're":'you are',
        'youre':'you are',
        "didn't":'did not',
        "i'll":'i will',
        "you'll":'you will',
        "youll":'you will',
        "it's":'it is',
        "don't":'do not',
        "i'm":'i am',
        'dnt':'do not',
        'frnds':'friends',
        'bday':'birthday',
        'wr':'where',
        'wt':'what',
        'wtf':'What the fuck',
        'pl':'please',
        'hw':'how',
        'coz':'because',
        'bcz': 'because',
        'cuz':'cause',
        'Idk':'i do not know',
        'idk':'i do not know',
        'bt':'but',
        'abt':'about',
        'bcoz':'because',
        'im':'i am',
        'U':'you',
        'r':'are',
        'R': 'are',
         ' b ':'be',
        'gf':'girlfriend',
        'bf':'boyfriend',
        'u':'you',
        'Ur':'Your',
        'wlcm':'Wellcome',
        'm8':'mate',
        'mgmt':'management',
        'mmfu':'my mate fancies you',
        'mob':'mobile',
        'msg':'message ',
        'msia':'malaysia',
        'mtfbwu':'may the force be with you',
        'mtg':'meeting',
        'mth':'month',
        'myob':'mind your own business',
        'n/a':'not applicable',
        'ne':'any',
        'ne1':'anyone',
        'nethng':'anything',
        'no1':'no one',
        'np':'no problem',
        'nvm':'never mind',
        'oic':'oh, i see',
        'omg':'oh, my god',
        'paw':'parents are watching',
        'pcm':'please call me',
        'pls':'please',
        'plz':'please',
        'plz4gvme':'please forgive me',
        'po$bl':'possible',
        'ppl':'people',
        'prl':'parents are listening',
        'puks':'pick up kids',
        'rgds':'regards',
        'ringl8':'running late',
        'rtfm':'read the flippin manual',
        'ru':'are you',
        'cmng':'coming',
        'ruok':'are you okay?',
        'shopn':'shopping',
        'sit':'stay in touch',
        'soz':'sorry',
        'spk':'speak',
        'stfu':'shut the flip up',
        'sum1':'someone',
        'tel':'telephone',
        'thanq':'thank you',
        'thkq':'thank you',
        'thx':'thanks',
        'tmb':'text me back',
        'tq':'thank you',
        'ttyl':'talk to you later',
        'tx':'thanks',
        'tyvm':'thank you very much',
        'u':'you',
        'ur':'your',
        'ura*':'you are a star',
        'uraqt':'you are a cutie',
        'w/':'with',
        'w/o':'without',
        'w8':'wait',
        'w84m':'wait for me',
        'wan2':'want to',
        'wan2tlk':'want to talk?',
        'wbs':'with',
        'wearing':'a walkman',
        'wel':'well',
        'wiv':'write back soon',
        'wknd':'weekend',
        'wot':'what',
        'wru':'where are you?',
        'wu':"what's up?",
        'wud?':'what you doing',
        'wygowm':'will you go out with me',
        'x':'kiss',
        'xlnt':'excellent',
        'xoxox':'hugs and kisses',
        'y':'why',
        'yr':'your',
        'yyssw':'yeah yeah sure sure whatever',
        '1ce':'once',
        '2':'to',
        '26y4u':'too sexy for you',
        '2day':'today',
        '2mor':'tomorrow',
        '2nite':'tonight',
        '3sum':'threesome',
        '4':'for',
        '911':'emergency - call me',
        'aka':'also known as',
        'asap':'as soon as possible',
        'atb':'all the best',
        'b':'be',
        'b4':'before',
        'b4n':'or bfn bye for now',
        'bbl':'be back later',
        'bcnu':'be seeing you',
        "b'day":'birthday',
        'bhl8':'be home late',
        'bil':'boss is listening',
        'brb':'be right back',
        'btdt':'been there done that',
        'btw':'by the way',
        'buzz':'off buzz off',
        'c':'see',
        'cid':'consider it done',
        'cmi':'call me',
        'ctr':'center',
        'cu':'see you',
        'cubl8r':'call you back later',
        'cul':'see you later',
        'cyr':'call your',
        'bos':'boss',
        'bro':'brother',
        'ma':'mother',
        'ofis':'office',
        'pa':'father',
        'wf':'wife',
        'don':'doing',
        'dylm':'do you like me',
        'ez':'easy',
        'f2f':'face to face',
        'f2t':'free to talk',
        'fotflol':'falling on the floor, laughing out loud',
        'fyi':'for your in from ation',
        'gal':'get a life',
        'grt':'great',
        'gtg':'got to go',
        'gudluk':'good luck',
        'h8':'hate',
        'hak':'hugs and kisses',
        'hand':'have a nice day',
        'hot4u':'hot for you',
        'hp':'handphone',
        'ic':'i see',
        'iluvu':'i love you',
        'im2gud4u':"i'm too good for you",
        'imho':'in my humble opinion',
        'imnsho':'in my not so humble opinion',
        'imtng':'in meeting',
        'iyq':'i like you',
        'jk':'just kidding',
        'jhb':'johannesburg',
        'jic':'just in case',
        'jk':'just kdding',
        'kit':'keep in touch',
        'kwim':'know what i mean',
        'l8':'late',
        'l8r':'later',
        'ldn':'london',
        'lol':'laughing out loud or loads of love',
        'lv':'love',
        'lying':'lyn',
        "you’re": 'you are',
        "You’re":  'You are',
        "You're": ' You are ',
        "you're":  " you are ",
        'S he':'she',
        'fe':'fell',
       "wouldn't": 'would not',
       "wouldn't": "would not",
       "aren’t": "are not",
       "we'd": " we should ",
       "should'veTaken": "should've Taken",
       "should've": "should have",
       'shouldnt': 'should not',
       "won't": "won not",
       "It’s": " It is ",
        "It's": " It is ",
        "it's": " it is ",
       "doesn’t": " dose not ",
       "Doesn’t": " Does not ",
        "What’s": " What is ",
       "what's": " what is ",
       "what’s": " what is ",
       "you've": " you have ",
       " w/u ": " you ",
        "he’s": " he is ",
       "He’s": " He is ",
        "He's": " He is ",
        "he's":  " he is ",
        "he’d": " he should ",
       "There's": " There is ",
        "there's": " there is ",
       "there’s": " there is ",
         "women's": " woman is ",
       "mom’s": " mom is ",
       "woman’s": " woman is ",
       "they’re": " they are ",
      "ain’t": " am not ",
     "God’s": " god is ",
     "God's": " god is ",
      "Ain’t": " am not ",
     "men's": " men is ",
    "weren't": " were not ",
     "That's": " That is ",
      "that’s": " that is ",
      "that's": " that is ",
       "That's": " that is ",
      "She's": " she is ",
         "she’s": " she is ",
     "she's": " she is ",
      "didn’t": " did not ",
    "don't": " do not ",
     "don’t": " do not ",
     "Don't": " Do not ",
       "doesn't": " does not ",
      "Don’t": " do not ",
      "didn't": " did not ",
     "Doesn't": " does not ",
     "I'll": " I will ",
     "I’ll": " I will ",
      "I'd": " I would ",
      "i’d": " i would ",
      "I’d": " I would ",
    "they'd": " they would ",
    "I’ve": " I have ",
    "I’m": " I am ",
    "i’m": " i am ",
    "I'm": " I am ",
    "I've": " i have ",
    "i'm": " i am ",
    "Let's": " Let is ",
    "Let’s": " let is ",
    "let’s": " let is ",
    "Isn't": " is not ",
    "won’t": " won not ",
    "can’t": " can not ",
     "can't": " can not ",
    "Can't": " can not ",
    "hadn't": " had not ",
    "wouldn’t": " would not ",
    "Shouldn't": " Should not ",
    "shouldn't": " should not ",
    "shouldn’t": " should not ",
    "aren't": " are not ",
    "It'd": " it would ",
    "wasn't": " was not ",
    "She’s": "She’s",
    "she’s": " she is ",
    "she's": " she is ",
    "prick's": " prick is ",
    "She’ll": " She will ",
    "she’ll": " she will ",
    "She's": " she is ",
    "hasn’t": " has not ",
    "Trump’s": " Trump is ",
    "it’ll": " it will ",
    "Couldn't": " Could not ",
    "couldn't": " could not ",
    "isn’t": " is not ",
    "Isn't": " Is not ",
    "isn't": " is not ",
    "Can't": " Can not ",
    "CAN'T": " can not ",
    "can't": " can not ",
    "weren’t": " were not ",
    "They're": " they are ",
    "they're": " they are ",
    "they'll": " they will ",
    " TV ": " Television ",
    "f**king": " fuck",
    "f**k": " fuck ",
    "f**ked": " fucked ",
    "#Trump2020": " trump 2020 ",
    "Ted's": " Ted is ",
    "Thomas's": " Thomas is ",
    "Trump's": " Trump is ",
    "#TrudeauMustGo": " trudeau must go ",
    "#DeepStateCorruption": " deep state corruption ",
    "#PutUpOrShutUp": " put up or shut up ",
    "#CallTheVoteAlready": " Call The Vote Already ",
    "Flynn’s": " Flynn is ",
    "#DangerousDemocrats": " Dangerous Democrats ",
    "#KavanaughConfirmation": " Kavanaugh Confirmation ",
    "#WakeUpAmerica": " Wake Up America ",
    "#CloserNation": " Closer Nation ",
    "#LeviStrauss": " Levi Strauss ",
    "sh*t": " shit ",
    "who's":" who is ",
    "#CrookedHillary": " Crooked Hillary ",
    "#ChristineBlaseyFord": " Christine Blasey Ford ",
    "SJWs": " Social Justice Warriors ",
    "#ConfirmKavanaugh": " Confirm Kavanaugh ",
    "fascist's": " fascist is ",
    "follower's": " follower is",
    "ball's": " ball is ",
    "Woodword's": " Woodword is ",
    "#machinelearning": " machine learning",
    "#ThursdayThoughts": " Thursday Thoughts ",
    "Non-voters": " Nonvoters ",
    "community's": " community is ",
    "Here's": " here is ",
    "here's": " here is ",
    "#DrainTheDeepState": " Drain The Deep State ",
    "#DrainTheSwamp": " Drain The Swamp ",
    "We've": " We have ",
    "We're": " we are ",
    "#brexitshambles": " brexit shambles ",
    "#BrexitMeansBrexit": " Brexit Means Brexit ",
    "you'll": " you will ",
    "#oshaeterry": " oshae terry ",
    "#ThugLife": " Thug Life ",
    "#MAGA2020": " MAGA 2020 ",
    "#MAGARallyRules": " MAGA Rally Rules ",
    "#TexasPolice": " Texas Police ",
    "didnt": " did not ",
    "Gemini's": " Gemini is ",
    "Y'all": " you and all ",
    "#proudtobeBritish": " proud to be British ",
    "OMG": " Oh My God! ",
    "#FrankOz": " Frank Oz ",
    "KKK": " Ku Klux Klan ",
    "LMAOOOO": "lmao",
    "LMAOOO": "lmao",
    "Lmaoooo": "lmao",
    "lmao": " Laughing My Ass Off ",
    "Lmao": " Laughing My Ass Off ",
    "LMAO": " Laughing My Ass Off ",
    "Dems": " Development Engineering Management System ",
    "dems": " Development Engineering Management System ",
    "uhm": " universal host machine ",
    "#ScotusKavenaugh": " Scotus Kavenaugh ",
    "#REDWAVERISING2018": " RED WAVE RISING 2018 ",
    "#NightMayor 's": " Night Mayor is ",
    "Nenshi’s": " Nenshi is ",
    "#fordnation": " ford nation ",
    "YESSSSSHHHHH": " yes ",
     "Lol": "lol",
    "lol": " Laugh Out Loud ",
    "CEO": " Chief Executive Officer ",
    "COO": " Chief Operating Officer ",
    "CBS": " Columbia Broadcasting System ",
    "needa": " need ",
    "Devil's": " Devil is ",
    " Ur ": " ultra rare ",
    " u ": " you ",
    "scotus": " Supreme Court of the United States ",
    "Fuck u": " fuck you ",
    "fuckin": " fuck ",
    "y'all's": " you and all is ",
    "peopl ehave": " people have ",
    " CA ": " Canada ",
    "GOP": " Grand Old Party ",
    "CNN": " Cable News Network ",
    "Budden's": " Budden is ",
    "M*neta's": "  Moneta is ",
    "haven’t": " have not ",
    " Tbh ": " to be honest ",
    " tbh ": " to be honest ",
    "CUCK": " a political neologism and term of abuse:white nationalists to insult Republican politicians who are too mainstream",
    "LOL": " laughing out loud ",
    "wanna": " want to ",
    "stick w it":" stick with it ",
    "SJW": " Social justice warrior ",
    "NDP": " New Democratic Party ",
    "Smh": "Shaking My Head",
    "WAPO": "White American Political Organization ",
    "SS": " Schutzstaffel ",
    "Mm": " millimeter ",
    "KP": " Kilometer Post ",
    "steepppp": " step ",
    "yyyy": " you ",
    "yep": " yes ",
    "bc": "British Columbia",
    "MF":" millifarad ",
    "DNC": "Democratic National Committee",
     "Shes": " she is ",
    "shes": " she is ",
     "RIP":" rest in peace ",
     "UFC": " Ultimate Fighting Championship ",
    "DC": " District of Columbia ",
    'NPR': "National Public Radio",
     "CIA": " Central Intelligence Agency ",
     "IRS": " Internal Revenue Service ",
      "idk": " I don not know",
     "f*ck": " fuck ",
"CFO":" Chief Financial Officer ",



}



def ekphrasis_config(str):


    social_tokenizer = SocialTokenizer(lowercase=True).tokenize
    str_list = social_tokenizer(str)
    # print(str_list)
    # for index in range(len(str_list)):
    #     str_list[index] = sp.correct(str_list[index])

    # for index in range(len(str_list)):
    #     if str_list[index] in EMOTICONS_TOKEN.keys():
    #         str_list[index] = EMOTICONS_TOKEN[str_list[index]]
    # for index in range(len(str_list)):
    #     if str_list[index] in EMOTICONS_TOKEN.keys():
    #         str_list[index] = EMOTICONS_TOKEN[str_list[index]][1:len(EMOTICONS_TOKEN[str_list[index]]) - 1]
    #
    # for index in range(len(str_list)):
    #     if str_list[index] in LOGOGRAM.keys():
    #         str_list[index] = LOGOGRAM[str_list[index]]


    return str_list
'''
if __name__ == '__main__':
    str = "}:) 3:-) good util 0:-),can't"
    print(ekphrasis_config(str))

'''
